import { BackToHome } from '@/components/layout/BackToHome';

const USES = [
  'Provide, operate, and maintain our website',
  'Improve, personalize, and expand our website',
  'Understand and analyze how you use our website',
  'Develop new products, services, features, and functionality',
  'Communicate with you, either directly or through one of our partners, including for customer service, to provide you with updates and other information relating to the website, and for marketing and promotional purposes',
  'Send you emails',
  'Find and prevent fraud',
];

const CCPA_RIGHTS = [
  "Request that a business that collects a consumer's personal data disclose the categories and specific pieces of personal data that a business has collected about consumers.",
  'Request that a business delete any personal data about the consumer that a business has collected.',
  "Request that a business that sells a consumer's personal data, not sell the consumer's personal data.",
];

const GDPR_RIGHTS = [
  'The right to access — You have the right to request copies of your personal data.',
  'The right to rectification — You have the right to request that we correct any information you believe is inaccurate.',
  'The right to erasure — You have the right to request that we erase your personal data, under certain conditions.',
  'The right to restrict processing — You have the right to request that we restrict the processing of your personal data, under certain conditions.',
  'The right to object to processing — You have the right to object to our processing of your personal data, under certain conditions.',
  'The right to data portability — You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions.',
];

const TERMS_CLAUSES = [
  {
    id: 'A',
    text: 'This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.',
  },
  {
    id: 'B',
    text: 'This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of our platform, including the related mobile site and mobile application (hereinafter referred to as "Platform").',
  },
  {
    id: 'C',
    text: 'The Platform is owned by Forte Digital Solutions LLP, a company incorporated under the Companies Act, 1956 with its registered office (hereinafter referred to as "Platform Owner", "we", "us", "our").',
  },
  {
    id: 'D',
    text: 'Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference.',
  },
  {
    id: 'E',
    text: 'For the purpose of these Terms of Use, wherever the context so requires "you", "your" or "user" shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.',
  },
  {
    id: 'F',
    text: 'ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.',
  },
];

export default function TermsAndConditions() {
  return (
    <div className="pt-24 pb-16 px-4 sm:px-6 max-w-3xl mx-auto">
      <BackToHome />

      <div className="mb-8">
        <h1 className="text-3xl sm:text-4xl font-black text-white mb-2">Terms and Conditions</h1>
        <p className="text-white/40 text-sm">Last Updated: 15-01-2026</p>
      </div>

      <div className="space-y-8 text-white/70 text-sm leading-relaxed">
        <p>
          At Forte Digital Solutions LLP, one of our main priorities is the privacy of our visitors.
          This Privacy Policy document contains types of information that is collected and recorded
          by our platform and how we use it.
        </p>
        <p>
          If you have additional questions or require more information about our Privacy Policy, do
          not hesitate to contact us.
        </p>
        <p>
          This Privacy Policy applies only to our online activities and is valid for visitors to
          our website with regards to the information that they shared and/or collect on our
          platform. This policy is not applicable to any information collected offline or via
          channels other than this website.
        </p>

        <section>
          <h2 className="text-white font-bold text-base mb-2">Consent</h2>
          <p>
            By using our website, you hereby consent to our Privacy Policy and agree to its terms.
          </p>
        </section>

        <section>
          <h2 className="text-white font-bold text-base mb-2">Information We Collect</h2>
          <p className="mb-3">
            The personal information that you are asked to provide, and the reasons why you are
            asked to provide it, will be made clear to you at the point we ask you to provide your
            personal information.
          </p>
          <p className="mb-3">
            If you contact us directly, we may receive additional information about you such as your
            name, email address, phone number, the contents of the message and/or attachments you
            may send us, and any other information you may choose to provide.
          </p>
          <p>
            When you register for an Account, we may ask for your contact information, including
            items such as name, company name, address, email address, and telephone number.
          </p>
        </section>

        <section>
          <h2 className="text-white font-bold text-base mb-3">How We Use Your Information</h2>
          <p className="mb-3">We use the information we collect in various ways, including to:</p>
          <ul className="space-y-2">
            {USES.map((item) => (
              <li key={item} className="flex items-start gap-2">
                <span className="text-primary shrink-0">›</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </section>

        <section>
          <h2 className="text-white font-bold text-base mb-2">Log Files</h2>
          <p>
            Our platform follows a standard procedure of using log files. These files log visitors
            when they visit websites. All hosting companies do this and a part of hosting
            services&apos; analytics. The information collected by log files include internet
            protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time
            stamp, referring/exit pages, and possibly the number of clicks. These are not linked to
            any information that is personally identifiable. The purpose of the information is for
            analyzing trends, administering the site, tracking users&apos; movement on the website,
            and gathering demographic information.
          </p>
        </section>

        <section>
          <h2 className="text-white font-bold text-base mb-2">Cookies and Web Beacons</h2>
          <p>
            Like any other website, our platform uses &apos;cookies&apos;. These cookies are used to
            store information including visitors&apos; preferences, and the pages on the website
            that the visitor accessed or visited. The information is used to optimize the users&apos;
            experience by customizing our web page content based on visitors&apos; browser type
            and/or other information.
          </p>
        </section>

        <section>
          <h2 className="text-white font-bold text-base mb-3">
            CCPA Privacy Rights (Do Not Sell My Personal Information)
          </h2>
          <p className="mb-3">
            Under the CCPA, among other rights, California consumers have the right to:
          </p>
          <ul className="space-y-2 mb-3">
            {CCPA_RIGHTS.map((item) => (
              <li key={item} className="flex items-start gap-2">
                <span className="text-primary shrink-0">›</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
          <p>
            If you make a request, we have one month to respond to you. If you would like to
            exercise any of these rights, please contact us.
          </p>
        </section>

        <section>
          <h2 className="text-white font-bold text-base mb-3">GDPR Data Protection Rights</h2>
          <p className="mb-3">
            We would like to make sure you are fully aware of all of your data protection rights.
            Every user is entitled to the following:
          </p>
          <ul className="space-y-2">
            {GDPR_RIGHTS.map((item) => (
              <li key={item} className="flex items-start gap-2">
                <span className="text-primary shrink-0">›</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </section>

        <section>
          <h2 className="text-white font-black text-lg mb-4">Terms and Conditions</h2>
          <div className="space-y-4">
            {TERMS_CLAUSES.map((clause) => (
              <div
                key={clause.id}
                className="rounded-xl border border-white/10 bg-zinc-900/40 p-4"
              >
                <span className="text-primary font-black text-sm mr-2">{clause.id}.</span>
                <span>{clause.text}</span>
              </div>
            ))}
          </div>
        </section>
      </div>
    </div>
  );
}
